baseURL = "https://moonselbee.netlify.app"
languageCode = 'en-us'
title = 'moonselbee'

[module]
[module.hugoVersion]
min = "0.148.0"

[Params]
mainSections = "post"
subtitle     = "test site for moon"

[menu]
[[menu.main]]
  name = 'about'
  url = '/page/about'
  weight = 10

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'post'