[build.environment]
GO_VERSION = "1.25.5"
HUGO_VERSION = "0.154.2"
NODE_VERSION = "24.12.0"
TZ = "GMT"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """