backend:
    name: github
    repo: sickcallfuu/moonselbee
media_folder: "static/media/uploads"
public_folder: "/media/uploads" 

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "posts" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { tags: "tags", name: "tags", widget: "list" }
      - { label: "body", name: "body", widget: "markdown" }

  - name: "page"
    label: "pages"
    folder: "page"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { tags: "tags", name: "tags", widget: "list" }
      - { label: "body", name: "body", widget: "markdown" }

  - name: "current" # Used in routes, e.g., /admin/collections/blog
    label: "current" # Used in the UI
    folder: "current" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { tags: "tags", name: "tags", widget: "list" }
      - { label: "body", name: "body", widget: "markdown" }
